AllCops:
  Exclude:
    - 'db/**/**'
    - 'config/**/**'
    - 'bin/*'
    - 'app/channels/application_cable/channel.rb'
    - 'app/channels/application_cable/connection.rb'
    - 'test/**/**.rb'
    - 'app/jobs/application_job.rb'
    - 'app/models/application_record.rb'
    - 'app/mailers/application_mailer.rb'
    - 'config.ru'
    - 'Rakefile'
    - 'Gemfile'
